version: "3"
services:
  postgres:
    image: postgres:latest
    networks:
      - postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - docker.env

  pgadmin:
    image: dpage/pgadmin4:6.18
    networks:
      - postgres
    ports:
      - "8080:80"
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - docker.env

  top-games-tracker:
    image: top-games-tracker
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - postgres  

networks:
  postgres:
    driver: bridge
      